### PR TITLE
return errors on delete command

### PR DESCRIPTION
**Pull request by robjloranger**
changes command for delete to return errors to the user

also updates comment for DoDelete

this is part of writeas/writefreely#117

### CODE REVIEW

**Comment by thebaer** [comment]
Thanks, good catch.

I know we're kind of inconsistent with what we use right now. But do you think it'd be better to use `return cli.NewExitError(...)`, as we do earlier in that func, instead? I'm kind of leaning that way.

**Comment by robjloranger** [comment]
That's probably the best way, should we change all occurrences in `CmdDelete`? and later update other commands as they are touched?

**Comment by thebaer** [comment]
I would just change it for the two instances in this PR, and then yeah, we'll update other places as they're touched.

(I say only these two places, because especially with multiple-line logs, there might've been a reason I went with the `log.ErrorlnQuit` -- I'm not sure off the top of my head.)

**Comment by robjloranger** [comment]
:+1:

**Comment by thebaer** [comment]
Perfect. Looks good to me!

**Pull request merged**
