### PR TITLE
list: Fetch user posts if authenticated

### LINKED ISSUE #13: Support fetching authenticated user's posts
**Overview**
Users should be able to see a list of anonymous posts owned by their account.

**Background**
Since account posts aren't stored locally, users will need to be able to fetch a list of posts on their account, so they can access the IDs of published posts to update or delete them with the CLI.

**Dependencies**
User authentication (#10).

TODO: Add a method to the [go-writeas](https://github.com/writeas/go-writeas) library to [retrieve an authenticated user's posts](https://developer.write.as/docs/api/?go#retrieve-user-39-s-posts). (issue: writeas/go-writeas#5)

**Implementation**
* When running `writeas list`, show these remote posts if a user is authenticated

The posts list should also be a little more useful by including post title / content, potentially behind a new CLI flag. Some ideas:

```
bxp4el2zng8h9    A Post Title
uy9f77u0v7o7d    This is the starting text of my post, truncated somewhere...
```
We could potentially include unsynced posts in the list, like on the web.
```
bxp4el2zng8h9    A Post Title
uy9f77u0v7o7d    This is the starting text of my post, truncated somewhere...
UNSYNCED
13nbyi9j3hu1z    Older Post
```

### PR DESCRIPTION
**Pull request by abhinav**
This changes the `writeas list` command to fetch the remote posts if the
user is authenticated.

The command line output was left largely as-is with one change: If the
post is not anonymous (has a slug and an associated collection), the
`-url` flag will print the collection-specific URL rather than the
general `write.as/$id` URL.

Resolves #13 

(Note: The PR was made against the develop branch because the `auth`
command hasn't been merged into master yet.)

### CODE REVIEW

**Comment by thebaer** [comment]
This looks great so far. Could you resolve the new merge conflicts? Then I'll test it out.

**Comment by abhinav** [comment]
Updated

**Comment by abhinav** [comment]
Hey, just checking in. Does this need anything else?

**Comment by robjloranger** [comment]
closing in favor of #29 only due to potential for large merge conflicts, and I missed this before I started.

@abhinav if you could I'd love your feedback on that PR.

**Comment by abhinav** [comment]
@robjloranger Thanks for letting me know. I won't have time to review
the change but I'm glad this feature is getting built!

**Pull request closed without merging**
