### PR TITLE
Use writeas.v2

### PR DESCRIPTION
**Pull request by abhinav**
Seems to me that the v2 branch of go-writeas is where new development
is being done so this changes writeas-cli over to use that.

It also introduces a go.mod and go.sum to pin to dependencies
consistently.

(Minor note about the imports: I ran [goimports][1] on those two files
so the imports were grouped into standard library and everything else.
Separating standard library and other imports into groups is suggested
in the [Go Wiki][2]. That said, I'm happy to reverse that if you prefer
your style.)

[1]: https://godoc.org/golang.org/x/tools/cmd/goimports
[2]: https://github.com/golang/go/wiki/CodeReviewComments#imports

### CODE REVIEW

**Comment by thebaer** [comment]
Thanks! I actually hadn't updated the `develop` branch in a while, and was doing all of my current work on `local-workflow`. So `develop` is up to date now for any future changes you want to make, and already points to `writeas.v2`. But I think the go.mod / go.sum additions are good ones. Maybe can create a PR just for those?

**Comment by thebaer** [comment]
As for goimports, if you want to run that on all files and update the [Coding conventions](https://github.com/writeas/writeas-cli/blob/master/.github/CONTRIBUTING.md#coding-conventions) to match, I think that's a fine change to make.

**Comment by thebaer** [comment]
Since the stated purpose of this PR is finished already, I'll close this. Feel free to create individual PRs for each of those other previously mentioned changes.

**Comment by abhinav** [comment]
Sounds good!

go.mod change: #21 
goimports: #22

**Pull request closed without merging**
